sudo: required
services:
  - docker

script:
  - docker build -t mjohnsonpqa/react-example2 .
  - docker images mjohnsonpqa/react-example2

before_deploy:
  - docker login -u mjohnsonpqa -p founded1997 

deploy:
  provider: script
  script: docker push mjohnsonpqa/react-example2
  on:
<<<<<<< HEAD
    branch: master  
=======
    branch: master
>>>>>>> b445f93e86227df79ba29ba7fb27f0bf9ccbd510
